---
include:
  - board: nice_nano_v2
    shield: corne_left nice_oled azoteq_tps65_central
    artifact-name: corne_left_rgb_firmware_isolation

  - board: nice_nano_v2
    shield: corne_right nice_oled azoteq_tps65_peripheral
    artifact-name: corne_right_rgb_firmware_isolation

  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: settings_reset
