manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: desales327
      url-base: https://github.com/deSales327
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3.0
      import: app/west.yml
    - name: zmk-driver-azoteq-iqs5xx
      remote: desales327
      revision: bec78d530d896d5244a26d7bb39cf3e3ed69e25c
  self:
    path: config
