manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: desales327
      url-base: https://github.com/deSales327
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3.0
      import: app/west.yml
    - name: zmk-driver-azoteq-iqs5xx
      remote: desales327
      revision: e73fb0ab7a55ddada91af12b5c10c15e9c0e7cde
  self:
    path: config
